version: "3.8"
services:
  flask:
    build: .
    command: gunicorn -w 1 -b 0.0.0.0:80 main:app --reload
    #command: flask run --host 0.0.0.0
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
    ports:
    - "80:80"
    volumes:
    - ./:/app
    - /app/venv
